Move parser tests to sudoers directory and test the tokenizer output too.

diff --git a/plugins/sudoers/Makefile.in b/plugins/sudoers/Makefile.in
--- a/plugins/sudoers/Makefile.in
+++ b/plugins/sudoers/Makefile.in
@@ -365,7 +365,66 @@ uninstall:
 check: $(TEST_PROGS) visudo testsudoers
 	@./check_iolog_path $(srcdir)/regress/iolog_path/data
 	@./check_fill
-	@for t in $(srcdir)/regress/*/test*.sh; do SRCDIR=$(srcdir) $(SHELL) $$t; done
+	@passed=0; failed=0; total=0; \
+	    for t in $(srcdir)/regress/sudoers/*.in; do \
+		dir=`dirname $$t`; \
+		dirbase=`basename $$dir`; \
+		base=`basename $$t .in`; \
+		out="$${base}.out"; \
+		toke="$${base}.toke"; \
+		./testsudoers -dt <$$t >$$out 2>$$toke; \
+		if cmp $$out $$dir/$$out.ok >/dev/null; then \
+		    passed=`expr $$passed + 1`; \
+		    echo "$$dirbase/$$base (parse): OK"; \
+		else \
+		    failed=`expr $$failed + 1`; \
+		    echo "$$dirbase/$$base: FAIL"; \
+		    diff $$out $$dir/$$out.ok; \
+		fi; \
+		total=`expr $$total + 1`; \
+		if cmp $$toke $$dir/$$toke.ok >/dev/null; then \
+		    passed=`expr $$passed + 1`; \
+		    echo "$$dirbase/$$base (toke): OK"; \
+		else \
+		    failed=`expr $$failed + 1`; \
+		    echo "$$dirbase/$$base (toke): FAIL"; \
+		    diff $$out $$dir/$$out.ok; \
+		fi; \
+		total=`expr $$total + 1`; \
+	    done; \
+	    echo "$$dirbase: $$passed/$$total tests passed; $$failed/$$total tests failed"
+	@passed=0; failed=0; total=0; \
+	    for t in $(srcdir)/regress/*/*.sh; do \
+		dir=`dirname $$t`; \
+		dirbase=`basename $$dir`; \
+		base=`basename $$t .sh`; \
+		out="$${base}.out"; \
+		err="$${base}.err"; \
+		$(SHELL) $$t >$$out 2>$$err; \
+		if cmp $$out $$dir/$$out.ok >/dev/null; then \
+		    passed=`expr $$passed + 1`; \
+		    echo "$$dirbase/$$base: OK"; \
+		else \
+		    failed=`expr $$failed + 1`; \
+		    echo "$$dirbase/$$base: FAIL"; \
+		    diff $$out $$dir/$$out.ok; \
+		fi; \
+		total=`expr $$total + 1`; \
+		if test -s $$dir/$$err.ok; then \
+		    if cmp $$err $$dir/$$err.ok >/dev/null; then \
+			passed=`expr $$passed + 1`; \
+			echo "$$dirbase/$$base (stderr): OK"; \
+		    else \
+			failed=`expr $$failed + 1`; \
+			echo "$$dirbase/$$base (stderr): FAIL"; \
+			diff $$out $$dir/$$out.ok; \
+		    fi; \
+		    total=`expr $$total + 1`; \
+		elif test -s $$err; then \
+		    cat $$err 1>&2; \
+		fi; \
+	    done; \
+	    echo "$$dirbase: $$passed/$$total tests passed; $$failed/$$total tests failed"
 
 clean:
 	-$(LIBTOOL) --mode=clean rm -f $(PROGS) *.lo *.o *.la *.a stamp-* core *.core core.* *.out
