Check JSON output of sudoers test files too.

diff --git a/plugins/sudoers/Makefile.in b/plugins/sudoers/Makefile.in
--- a/plugins/sudoers/Makefile.in
+++ b/plugins/sudoers/Makefile.in
@@ -381,6 +381,7 @@ check: $(TEST_PROGS) visudo testsudoers
 		base=`basename $$t .in`; \
 		out="regress/sudoers/$${base}.out"; \
 		toke="regress/sudoers/$${base}.toke"; \
+		json="regress/sudoers/$${base}.json"; \
 		./testsudoers -dt <$$t >$$out 2>$$toke || true; \
 		if cmp $$out $(srcdir)/$$out.ok >/dev/null; then \
 		    passed=`expr $$passed + 1`; \
@@ -400,6 +401,16 @@ check: $(TEST_PROGS) visudo testsudoers
 		    diff $$toke $(srcdir)/$$toke.ok || true; \
 		fi; \
 		total=`expr $$total + 1`; \
+		./visudo -f $$t -x - >$$json 2>/dev/null || true; \
+		total=`expr $$total + 1`; \
+		if cmp $$json $(srcdir)/$$json.ok >/dev/null; then \
+		    passed=`expr $$passed + 1`; \
+		    echo "$$dir/$$base (parse): OK"; \
+		else \
+		    failed=`expr $$failed + 1`; \
+		    echo "$$dir/$$base: FAIL"; \
+		    diff $$json $(srcdir)/$$json.ok || true; \
+		fi; \
 	    done; \
 	    echo "$$dir: $$passed/$$total tests passed; $$failed/$$total tests failed"; \
 	    if test $$failed -ne 0; then \
