Add line continuation support to sudo_parseln() and make it use getline() instead of fgets() internally.

diff --git a/common/Makefile.in b/common/Makefile.in
--- a/common/Makefile.in
+++ b/common/Makefile.in
@@ -1,5 +1,5 @@
 #
-# Copyright (c) 2011 Todd C. Miller <Todd.Miller@courtesan.com>
+# Copyright (c) 2011-2013 Todd C. Miller <Todd.Miller@courtesan.com>
 #
 # Permission to use, copy, modify, and distribute this software for any
 # purpose with or without fee is hereby granted, provided that the above
@@ -54,6 +54,11 @@ PIE_LDFLAGS = @PIE_LDFLAGS@
 SSP_CFLAGS = @SSP_CFLAGS@
 SSP_LDFLAGS = @SSP_LDFLAGS@
 
+# Regression tests
+TEST_PROGS = parseln_test
+TEST_LIBS = @LIBS@ @LIBINTL@
+TEST_LDFLAGS = @LDFLAGS@
+
 # OS dependent defines
 DEFS = @OSDEFS@ -D_PATH_SUDO_CONF=\"$(sysconfdir)/sudo.conf\"
 
@@ -64,6 +69,8 @@ SHELL = @SHELL@
 LTOBJS = alloc.lo atobool.lo error.lo fileops.lo fmt_string.lo lbuf.lo list.lo \
 	 secure_path.lo setgroups.lo sudo_conf.lo sudo_debug.lo sudo_printf.lo \
 	 term.lo ttysize.lo zero_bytes.lo @COMMON_OBJS@
+
+PARSELN_TEST_OBJS = parseln_test.lo
 
 all: libcommon.la
 
@@ -77,6 +84,9 @@ Makefile: $(srcdir)/Makefile.in
 
 libcommon.la: $(LTOBJS)
 	$(LIBTOOL) --mode=link $(CC) -o $@ $(LTOBJS) -no-install
+
+parseln_test: $(PARSELN_TEST_OBJS) libcommon.la
+	$(LIBTOOL) --mode=link $(CC) -o $@ $(PARSELN_TEST_OBJS) libcommon.la $(TEST_LDFLAGS) $(TEST_LIBS)
 
 pre-install:
 
@@ -94,7 +104,28 @@ install-plugin:
 
 uninstall:
 
-check:
+check: $(TEST_PROGS)
+	@if test X"$(cross_compiling)" != X"yes"; then \
+	    passed=0; failed=0; total=0; \
+	    dir=sudo_parseln; \
+	    mkdir -p regress/$$dir; \
+	    for t in $(srcdir)/regress/$$dir/*.in; do \
+		base=`basename $$t .in`; \
+		out="regress/$$dir/$$base.out"; \
+		./parseln_test <$$t >$$out; \
+		if cmp $$out $(srcdir)/$$out.ok >/dev/null; then \
+		    passed=`expr $$passed + 1`; \
+		    echo "$$dir/$$base: OK"; \
+		else \
+		    failed=`expr $$failed + 1`; \
+		    echo "$$dir/$$base: FAIL"; \
+		    diff $$out $(srcdir)/$$out.ok; \
+		fi; \
+		total=`expr $$total + 1`; \
+	    done; \
+	    echo "$$dir: $$passed/$$total tests passed; $$failed/$$total tests failed"; \
+	    exit $$failed; \
+	fi
 
 clean:
 	-$(LIBTOOL) --mode=clean rm -f *.lo *.o *.la *.a stamp-* core *.core core.*
@@ -140,6 +171,10 @@ lbuf.lo: $(srcdir)/lbuf.c $(top_builddir)/config.h $(incdir)/missing.h \
 list.lo: $(srcdir)/list.c $(top_builddir)/config.h $(incdir)/missing.h \
          $(incdir)/list.h $(incdir)/error.h
 	$(LIBTOOL) --mode=compile $(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) $(PIE_CFLAGS) $(SSP_CFLAGS) $(DEFS) $(srcdir)/list.c
+parseln_test.lo: $(srcdir)/regress/sudo_parseln/parseln_test.c \
+                 $(top_builddir)/config.h $(top_srcdir)/compat/stdbool.h \
+                 $(incdir)/missing.h $(incdir)/fileops.h
+	$(LIBTOOL) --mode=compile $(CC) -c -o $@ $(CPPFLAGS) $(CFLAGS) $(PIE_CFLAGS) $(SSP_CFLAGS) $(DEFS) $(srcdir)/regress/sudo_parseln/parseln_test.c
 secure_path.lo: $(srcdir)/secure_path.c $(top_builddir)/config.h \
                 $(incdir)/missing.h $(incdir)/sudo_debug.h \
                 $(incdir)/secure_path.h
